name: Testing

on:
  pull_request:
    branches:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          echo ${{ github.event.pull_request.base.ref }}