name: Testing

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout variables
        run: |
          echo ${{ github.event_name }}
          echo /repos/${{ github.repository_owner }}/${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}/pulls/${{ github.event.pull_request.number }}/comments
      
      - name: Add Issue Comment
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Hello, World!"
            })

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          pytest tests

  need-to-approve:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    steps:
      - name: echo
        run: echo "Need to approve"
